#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : moreutils
Version  : 0.67
Release  : 8
URL      : https://mirrors.kernel.org/debian/pool/main/m/moreutils/moreutils_0.67.orig.tar.gz
Source0  : https://mirrors.kernel.org/debian/pool/main/m/moreutils/moreutils_0.67.orig.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0 MIT
Requires: moreutils-bin = %{version}-%{release}
Requires: moreutils-license = %{version}-%{release}
BuildRequires : docbook-xml
Patch1: noman.patch

%description
This is a collection of the unix tools that nobody thought to write
long ago, when unix was young. Currently it consists of these tools:

%package bin
Summary: bin components for the moreutils package.
Group: Binaries
Requires: moreutils-license = %{version}-%{release}

%description bin
bin components for the moreutils package.


%package license
Summary: license components for the moreutils package.
Group: Default

%description license
license components for the moreutils package.


%prep
%setup -q -n moreutils-0.67
cd %{_builddir}/moreutils-0.67
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1648486569
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1648486569
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/moreutils
cp %{_builddir}/moreutils-0.67/COPYING %{buildroot}/usr/share/package-licenses/moreutils/4d1d37f306ed270cda5b2741fac3abf0a7b012e5
cp %{_builddir}/moreutils-0.67/debian/copyright %{buildroot}/usr/share/package-licenses/moreutils/a64a131d9ade2f0f8270db628aa0f845ca89a1ec
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/parallel

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/chronic
/usr/bin/combine
/usr/bin/errno
/usr/bin/ifdata
/usr/bin/ifne
/usr/bin/isutf8
/usr/bin/lckdo
/usr/bin/mispipe
/usr/bin/pee
/usr/bin/sponge
/usr/bin/ts
/usr/bin/vidir
/usr/bin/vipe
/usr/bin/zrun

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/moreutils/4d1d37f306ed270cda5b2741fac3abf0a7b012e5
/usr/share/package-licenses/moreutils/a64a131d9ade2f0f8270db628aa0f845ca89a1ec
